spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/legalease
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:your-super-secret-key-that-is-at-least-32-characters-long-for-security}
  expiration: ${JWT_EXPIRATION_MS:3600000}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.legalease: DEBUG
    org.springframework.security: DEBUG